services:
  mysql:
    image: mysql:8.4.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
      # - ./sample/world.sql:/docker-entrypoint-initdb.d/world.sql
    ports:
      - 3306:3306
volumes:
  db-data: