version: '3.8'
services:
  mysql:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db-data: